### ISSUE TITLE
Create backend API routes which act as a RP server

### ISSUE THREAD

**Issue by kwajiehao** [opengovsg/sgid-test-app#84]
## Problem

Currently, the sgID test app exposes server-side rendered endpoints which display the data retrieved from sgID. However, this couples the **rendering** and the **OIDC flow** of token exchange and userinfo retrieval. 

This issue supports issue https://github.com/datagovsg/sgid-server/issues/409

## Proposed solution

Create a new API route which handles the OIDC callback specifically, and refactor the existing SSR route to call this internal route for the OIDC flow

**Comment by PrawiraGenestonlia** [comment]
Require review: https://github.com/opengovsg/sgid-test-app/pull/90
